### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

### ISSUE THREAD

**Issue by SilentAssassin101** [YoCodingMonster/MSI-Dragon-Center-for-Linux#185]
Zorin OS 17.1 Core
Open Freeze Center 5
MSI Stealth 15M
Intel i7-11375H

$ ~/Downloads/OpenFreezeCenter-5/install.sh
----------EC read/write is enabled----------
----------Running Software----------
nohup: ignoring input and appending output to 'nohup.out'

$ sudo tail -f ./Desktop/nohup.out
File "/home/user/Desktop/OFC/OFC.py", line 20, in read
    with open(EC_IO_FILE,'r+b') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Desktop/OFC/OFC.py", line 108, in <module>
    import config
ModuleNotFoundError: No module named 'config'

$ sudo ls /sys/kernel/debug/ec
ls: cannot access '/sys/kernel/debug/ec': No such file or directory

-----
I have tried uninstalling, reinstalling, restarted my laptop, etc.

Seems very similar to this issue: https://github.com/YoCodingMonster/OpenFreezeCenter/issues/182#issue-2104918216

**Comment by SilentAssassin101** [comment]
# FOUND FIX
Disabling Secure Boot in BIOS fixed this
