### ISSUE TITLE
ISSUE # [Intel® Core™ i7-8750H × 12] - [MSI GL63 8RE] - [Ubuntu 24.10] 

### ISSUE THREAD

**Issue by Auroraa-42** [YoCodingMonster/MSI-Dragon-Center-for-Linux#188]
I have not been able to get OFC or OFC Lite to run on my system. The installer spawns nano, which inserts one line of text and gives me a "Can't Bind Key" error message in red at the bottom. It sits for about 20 seconds and then does it again, displaying a nano window with one line of text and the same error message. It ends the second instance of nano, drops me back to the prompt and doesn't run. Included is the nohup.out file. I have been trying to figure this out for days now. Every time I attempt to satisfy the dependencies for gi and config, the system tells me there's already something providing them. 

```
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 91, in <module>
    open(PATH_TO_CONFIG, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/aurora/Desktop/OFC/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 96, in <module>
    LINE_NO = "PROFILE = 1\nAUTO_SPEED = [["+str(read(0x72, 1, 0))+", "+str(read(0x73, 1, 0))+", "+str(read(0x74, 1, 0))+", "+str(read(0x75, 1, 0))+", "+str(read(0x76, 1, 0))+", "+str(read(0x77, 1, 0))+", "+str(read(0x78, 1, 0))+"], ["+str(read(0x8a, 1, 0))+", "+str(read(0x8b, 1, 0))+", "+str(read(0x8c, 1, 0))+", "+str(read(0x8d, 1, 0))+", "+str(read(0x8e, 1, 0))+", "+str(read(0x8f, 1, 0))+", "+str(read(0x90, 1, 0))+"]]"
                                                 ^^^^^^^^^^^^^^^^
  File "/home/aurora/Desktop/OFC/OFC.py", line 20, in read
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 108, in <module>
    import config
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 91, in <module>
    open(PATH_TO_CONFIG, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/aurora/Desktop/OFC/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 96, in <module>
    LINE_NO = "PROFILE = 1\nAUTO_SPEED = [["+str(read(0x72, 1, 0))+", "+str(read(0x73, 1, 0))+", "+str(read(0x74, 1, 0))+", "+str(read(0x75, 1, 0))+", "+str(read(0x76, 1, 0))+", "+str(read(0x77, 1, 0))+", "+str(read(0x78, 1, 0))+"], ["+str(read(0x8a, 1, 0))+", "+str(read(0x8b, 1, 0))+", "+str(read(0x8c, 1, 0))+", "+str(read(0x8d, 1, 0))+", "+str(read(0x8e, 1, 0))+", "+str(read(0x8f, 1, 0))+", "+str(read(0x90, 1, 0))+"]]"
                                                 ^^^^^^^^^^^^^^^^
  File "/home/aurora/Desktop/OFC/OFC.py", line 20, in read
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 108, in <module>
    import config
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 91, in <module>
    open(PATH_TO_CONFIG, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/aurora/Desktop/OFC/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 96, in <module>
    LINE_NO = "PROFILE = 1\nAUTO_SPEED = [["+str(read(0x72, 1, 0))+", "+str(read(0x73, 1, 0))+", "+str(read(0x74, 1, 0))+", "+str(read(0x75, 1, 0))+", "+str(read(0x76, 1, 0))+", "+str(read(0x77, 1, 0))+", "+str(read(0x78, 1, 0))+"], ["+str(read(0x8a, 1, 0))+", "+str(read(0x8b, 1, 0))+", "+str(read(0x8c, 1, 0))+", "+str(read(0x8d, 1, 0))+", "+str(read(0x8e, 1, 0))+", "+str(read(0x8f, 1, 0))+", "+str(read(0x90, 1, 0))+"]]"
                                                 ^^^^^^^^^^^^^^^^
  File "/home/aurora/Desktop/OFC/OFC.py", line 20, in read
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 108, in <module>
    import config
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 91, in <module>
    open(PATH_TO_CONFIG, "r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/aurora/Desktop/OFC/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 96, in <module>
    LINE_NO = "PROFILE = 1\nAUTO_SPEED = [["+str(read(0x72, 1, 0))+", "+str(read(0x73, 1, 0))+", "+str(read(0x74, 1, 0))+", "+str(read(0x75, 1, 0))+", "+str(read(0x76, 1, 0))+", "+str(read(0x77, 1, 0))+", "+str(read(0x78, 1, 0))+"], ["+str(read(0x8a, 1, 0))+", "+str(read(0x8b, 1, 0))+", "+str(read(0x8c, 1, 0))+", "+str(read(0x8d, 1, 0))+", "+str(read(0x8e, 1, 0))+", "+str(read(0x8f, 1, 0))+", "+str(read(0x90, 1, 0))+"]]"
                                                 ^^^^^^^^^^^^^^^^
  File "/home/aurora/Desktop/OFC/OFC.py", line 20, in read
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
ERROR: unknown command "OFC.Py"
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OpenFreezeCenter-Lite.py", line 113, in <module>
    CONFIG_FILE = open(PATH_TO_CONFIG, "r")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/aurora/Desktop/OFC/config.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OpenFreezeCenter-Lite.py", line 118, in <module>
    AUTO_SPEED_CPU = [ECT.read(0x72, 1), ECT.read(0x73, 1), ECT.read(0x74, 1), ECT.read(0x75, 1), ECT.read(0x76, 1), ECT.read(0x77, 1), ECT.read(0x78, 1)] # CPU FAN speed at LOWEST, LOWER, LOW, MEDIUM, HIGH, HIGHER, HIGHEST CPU TEMP
                      ^^^^^^^^^^^^^^^^^
  File "/home/aurora/Desktop/OFC/lib/python3.12/site-packages/ECTweaker.py", line 39, in read
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OpenFreezeCenter-Lite.py", line 133, in <module>
    import config
ModuleNotFoundError: No module named 'config'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Traceback (most recent call last):
  File "/home/aurora/Desktop/OFC/OFC.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by YoCodingMonster** [comment]
Please disable secure boot from bios
